name: Build Hugo site

on:
  push:
    branches: [ hugo-source ]

jobs:
  transform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true
        fetch-depth: 1
    - name: Update submodules
      run: |
        git pull --recurse-submodules --depth 1
        git submodule update --recursive --remote
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: "0.94.2"
        # extended: true
      # Step 3 - Clean and don't fail
    - name: Clean build_github directory
      run: rm -rf build_github
    - name: Build hugo site pages
      run: |
        hugo
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build_github
        publish_branch: master